Throwing error message incase of lengthy payload
cloudflare/matched-data-cli pull request #19
Opened 2022-02-10 10:27 UTC by shreyavshetty

Payload match exceeding a certain limit will be truncated and the changes are made to throw an error message for the same.

2022-02-10 11:54 UTC, migueldemoura commented
Builds are failing, can you run `cargo fmt`?

2022-02-10 11:58 UTC, migueldemoura requested changes

2022-02-10 11:58 UTC, migueldemoura commented on src/main.rs
> +       let encrypted_matched_data_file_truncated = temp_dir.child("encrypted_matched_data_truncated.txt");
Should we move this to its own test?

2022-02-10 11:58 UTC, migueldemoura commented on src/main.rs
> +            if matched_data_base64 == "truncated" {
nit: Should `truncated` be a const?

2022-02-11 12:56 UTC, migueldemoura approved these changes

2022-02-11 12:57 UTC, migueldemoura commented
Can you sign your commits, @shreyavshetty (and merge the 1st and 2nd ones as the truncation bit, and rename the 3rd one to "Update dependencies" or something similar)?

2022-02-14 23:25 UTC, shreyavshetty commented
> Can you sign your commits, @shreyavshetty (and merge the 1st and 2nd ones as the truncation bit, and rename the 3rd one to "Update dependencies" or something similar)?

Squashed to one, and signed

2022-02-15 12:53 UTC, merged